docker-compose.yml:
version: '2'
services:
   web:
      build: . 
      volumes:
             ./open-flights
      ports:
           "3000:3000"
      environment:
      DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$my_postgres_db
      depends_on:
      - db
   db:
     image: postgres: 11.4-alpine
     environment:
      POSTGRES_USER: admin  
      POSTGRES_PASSWORD: password  
      POSTGRES_DB: my_postgres_db  
     volumes:
      - postgres_data:/var/lib/postgresql/data
